// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Notification struct {
	ID            uuid.UUID
	Channel       string
	Recipient     string
	Template      string
	Variables     string
	Status        string
	Priority      string
	ScheduledAt   sql.NullTime
	RetryCount    int32
	MaxRetry      int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	SentAt        sql.NullTime
	FailureReason sql.NullString
}

type Template struct {
	ID        uuid.UUID
	Name      string
	Channel   string
	Subject   string
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
