// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notfication.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const dBUpdateNotificationStatus = `-- name: DBUpdateNotificationStatus :execresult
UPDATE notifications
SET status=$2
WHERE id=$1
RETURNING id, channel, recipient, template, variables, status, priority, scheduled_at, retry_count, max_retry, created_at, updated_at, sent_at, failure_reason
`

type DBUpdateNotificationStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) DBUpdateNotificationStatus(ctx context.Context, arg DBUpdateNotificationStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, dBUpdateNotificationStatus, arg.ID, arg.Status)
}

const dbCreateNotification = `-- name: DbCreateNotification :one
INSERT INTO notifications(id,channel,recipient,template,variables,priority,status)
VALUES ($1,$2,$3,$4,$5,$6,$7)
    RETURNING id, channel, recipient, template, variables, status, priority, scheduled_at, retry_count, max_retry, created_at, updated_at, sent_at, failure_reason
`

type DbCreateNotificationParams struct {
	ID        uuid.UUID
	Channel   string
	Recipient string
	Template  string
	Variables string
	Priority  string
	Status    string
}

func (q *Queries) DbCreateNotification(ctx context.Context, arg DbCreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, dbCreateNotification,
		arg.ID,
		arg.Channel,
		arg.Recipient,
		arg.Template,
		arg.Variables,
		arg.Priority,
		arg.Status,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Recipient,
		&i.Template,
		&i.Variables,
		&i.Status,
		&i.Priority,
		&i.ScheduledAt,
		&i.RetryCount,
		&i.MaxRetry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
		&i.FailureReason,
	)
	return i, err
}

const dbGetNotificationById = `-- name: DbGetNotificationById :one
SELECT id, channel, recipient, template, variables, status, priority, scheduled_at, retry_count, max_retry, created_at, updated_at, sent_at, failure_reason
FROM notifications
WHERE id=$1
`

func (q *Queries) DbGetNotificationById(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, dbGetNotificationById, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Recipient,
		&i.Template,
		&i.Variables,
		&i.Status,
		&i.Priority,
		&i.ScheduledAt,
		&i.RetryCount,
		&i.MaxRetry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
		&i.FailureReason,
	)
	return i, err
}
