// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: template.sql

package queries

import (
	"context"
)

const dbGetTemplate = `-- name: DbGetTemplate :one
SELECT id, name, channel, subject, body, created_at, updated_at
FROM templates
WHERE channel=$1 AND name=$2
`

type DbGetTemplateParams struct {
	Channel string
	Name    string
}

func (q *Queries) DbGetTemplate(ctx context.Context, arg DbGetTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, dbGetTemplate, arg.Channel, arg.Name)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.Subject,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
